- name: Ejecutar SIME
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          HORA=$(date +%H)
          # Corre en tus horas UTC: 00 (21hs AR), 11 (08hs AR), 14, 17, 20, 23
          if [[ "$HORA" == "00" || "$HORA" == "11" || "$HORA" == "14" || "$HORA" == "17" || "$HORA" == "20" || "$HORA" == "23" ]]; then
            python bot_github.py
          else
            echo "Fuera de horario para SIME. Saltando..."
          fi
        shell: bash
