- name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add vistos.txt agendados.json cursos_vistos.txt
          git commit -m "Actualizar memorias" || exit 0
          git push
